# https://medium.com/@MicroPyramid/set-up-travis-ci-for-django-project-427d6dd2f46c
# https://github.com/ndarville/pony-forum/blob/master/.travis.yml
dist:           xenial   # required for Python >= 3.7
language:       python
python:
  - "3.7"
# Start PostgreSQL
services:
    - postgresql
# Specify Django version and the database
env:
    global:
        - DJANGO_SETTINGS_MODULE="representable.settings"
        - PYTHONPATH="/home/travis/build/representable/representable"
        - PIP_USE_MIRRORS=true
# Install the version of PostGIS that matches your PostgreSQL version,
# and activate the PostGIS extension using:
addons:
  postgresql: "11.2"
  apt:
    packages:
    - postgresql-11-postgis-2.5

# command to install dependencies
install:
  - pip install -r requirements.txt

# Run before script.
before_script:
    - psql --version
    - psql -c 'create database travis_ci_test;' -U postgres
    - psql -U postgres -c "create extension postgis;"

# command to run tests
script:
  - python manage.py test

# Email settings
notifications:
  email:
    recipients:
      - representableteam@gmail.com
    on_success: never
    on_failure: always
