# https://medium.com/@MicroPyramid/set-up-travis-ci-for-django-project-427d6dd2f46c
# https://github.com/ndarville/pony-forum/blob/master/.travis.yml
dist:           xenial   # required for Python >= 3.7
language:       python
python:
  - "3.7"

env:
    global:
        - DJANGO_SETTINGS_MODULE="representable.settings"
        - PYTHONPATH="/home/travis/build/representable/representable"
        - PIP_USE_MIRRORS=true
        - SECRET_KEY="testkey-travisci"
        - PGPORT=5433
        - PGVER=12

# Install the version of PostGIS that matches your PostgreSQL version,
# and activate the PostGIS extension using:
addons:
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts

# command to install dependencies

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart
  - sh -c 'until pg_isready -p 5433; do echo "Wait for Postgres to restart"; sleep 2; done'
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis;"
  
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python3 manage.py collectstatic --settings=representable.settings.dev
  - python3 manage.py test --settings=representable.settings.dev
