# Generated by Django 2.2 on 2019-04-27 14:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityentry',
            old_name='entry_polygon',
            new_name='user_polygon',
        ),
        migrations.AddField(
            model_name='communityentry',
            name='census_blocks_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('', 'Issue Category'), ('criminal_justice', 'Criminal Justice'), ('civil_rights', 'Civil Rights'), ('economic', 'Economic Affairs'), ('education', 'Education'), ('environment', 'Environment'), ('health', 'Health and Health Insurance'), ('internet', 'Internet Regulation'), ('women', "Women's Issues"), ('lgbt', 'LGBT Issues'), ('security', 'National Security'), ('welfare', 'Social Welfare')], default=None, max_length=50),
        ),
    ]
