# Generated by Django 2.2.6 on 2019-12-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
