# Generated by Django 2.2 on 2019-04-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communityentry',
            table='community_entry',
        ),
    ]
