# Generated by Django 2.1.7 on 2019-04-05 16:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='race',
        ),
        migrations.AddField(
            model_name='community',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black or African American'), ('native', 'American Indian or Alaska Native'), ('pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('asian', 'Asian')], max_length=50), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
