# Generated by Django 2.2 on 2019-04-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='creator',
            new_name='creator_ID',
        ),
    ]
