# Generated by Django 2.2 on 2019-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='entry_issues',
            field=models.ManyToManyField(to='main.Issue'),
        ),
    ]
