# Generated by Django 2.2 on 2019-04-11 23:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190411_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=5)),
                ('race', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black or African American'), ('native', 'American Indian or Alaska Native'), ('pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('Asian', (('indian', 'Asian Indian'), ('chinese', 'Chinese'), ('filipino', 'Filipino'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('other_asian', 'Other Asian'))), ('other', 'Other')], max_length=50), default=list, size=None)),
                ('issues', models.CharField(max_length=100)),
                ('is_my_community', models.BooleanField()),
            ],
        ),
    ]
