# Generated by Django 2.2 on 2019-04-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_communityentry_entry_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityentry',
            name='issue_list',
        ),
    ]
