# Generated by Django 2.2.6 on 2019-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_communityentry_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='entry_name',
            field=models.CharField(default='Community name', max_length=100),
        ),
        migrations.AddField(
            model_name='communityentry',
            name='entry_reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
