# Generated by Django 2.2.6 on 2020-05-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20191219_1156"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Issue",
        ),
    ]
