# Generated by Django 2.2 on 2019-05-11 22:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190511_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='census_blocks_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
