# Generated by Django 2.2.6 on 2019-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='entry_name',
            field=models.CharField(blank=True, default='Community_name', max_length=100),
        ),
    ]
