# Generated by Django 2.1.7 on 2019-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190405_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
