# Generated by Django 2.2 on 2019-04-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_issue_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.CommunityEntry'),
        ),
    ]
