# Generated by Django 2.2 on 2019-04-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190427_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Issue Category'), ('criminal_justice', 'Criminal Justice'), ('civil_rights', 'Civil Rights'), ('economic', 'Economic Affairs'), ('education', 'Education'), ('environment', 'Environment'), ('health', 'Health and Health Insurance'), ('internet', 'Internet Regulation'), ('women', "Women's Issues"), ('lgbt', 'LGBT Issues'), ('security', 'National Security'), ('welfare', 'Social Welfare')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='entry',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='main.CommunityEntry'),
        ),
    ]
