# Generated by Django 2.2.4 on 2020-04-09 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ext_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="link",
            field=models.CharField(
                default="test",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9-]*$",
                        "Enter a valid link with only numbers, letters, and dashes (-).",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
