# Generated by Django 2.2.6 on 2020-05-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_delete_issue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityentry", name="my_community",
        ),
    ]
