# Generated by Django 2.1.7 on 2019-04-05 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190405_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='race',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('white', 'White'), ('black', 'Black or African American'), ('native', 'American Indian or Alaska Native'), ('pacific_islander', 'Native Hawaiian or Other Pacific Islander'), ('Asian', (('indian', 'Asian Indian'), ('chinese', 'Chinese'), ('filipino', 'Filipino'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('vietnamese', 'Vietnamese'), ('other_asian', 'Other Asian'))), ('other', 'Other')], max_length=50), default=list, size=None),
        ),
    ]
