# Generated by Django 2.2 on 2019-04-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_communityentry_issue_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='name',
            new_name='title',
        ),
    ]
