# Generated by Django 2.2 on 2019-04-18 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190418_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='industry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('agriculture', 'Agriculture'), ('forestry', 'Forestry'), ('fishing', 'Fishing'), ('mining', 'Mining'), ('utilities', 'Utilities (Power, Natural Gas)'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('professional', 'Professional (Scientific/Technical) Services'), ('arts', 'Arts'), ('other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
