# Generated by Django 2.2 on 2019-04-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190418_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='my_community',
            field=models.CharField(choices=[('Y', 'This is my community'), ('N', 'I am creating this community on behalf of another group of people')], default='Y', max_length=1, verbose_name='Is this your community?'),
        ),
    ]
