# Generated by Django 2.2.6 on 2019-12-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191218_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='entry_reason',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
