# Generated by Django 2.2 on 2019-05-12 13:59

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190512_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='census_blocks_polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='communityentry',
            name='census_blocks_polygon_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='communityentry',
            name='user_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
    ]
