# Generated by Django 2.2 on 2019-04-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190413_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('category', 'title')},
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('criminal_justice', 'Criminal Justice'), ('civil_rights', 'Civil Rights'), ('economic', 'Economic Affairs'), ('education', 'Education'), ('environment', 'Environment'), ('energy', 'Energy'), ('health', 'Health and Health Insurance'), ('internet', 'Internet Regulation'), ('women', "Women's Issues"), ('lgbt', 'LGBT Issues'), ('security', 'National Security'), ('welfare', 'Social Welfare')], default=None, max_length=50),
        ),
    ]
