# Generated by Django 2.2 on 2019-05-08 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190508_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityentry',
            name='census_blocks_polygon_array',
        ),
        migrations.AddField(
            model_name='communityentry',
            name='census_blocks_multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
