# Generated by Django 2.2 on 2019-05-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190428_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='zipcode',
            field=models.CharField(max_length=5, verbose_name='Zipcode'),
        ),
    ]
