# Generated by Django 2.2 on 2019-05-08 14:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190508_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityentry',
            name='census_blocks_multipolygon',
        ),
        migrations.AddField(
            model_name='communityentry',
            name='census_blocks_polygon_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326), blank=True, null=True, size=None),
        ),
    ]
