# Generated by Django 2.2 on 2019-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190416_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('category', 'description')},
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('criminal_justice', 'Criminal Justice'), ('civil_rights', 'Civil Rights'), ('economic', 'Economic Affairs'), ('education', 'Education'), ('environment', 'Environment'), ('health', 'Health and Health Insurance'), ('internet', 'Internet Regulation'), ('women', "Women's Issues"), ('lgbt', 'LGBT Issues'), ('security', 'National Security'), ('welfare', 'Social Welfare')], default=None, max_length=50),
        ),
    ]
