# Generated by Django 2.2 on 2019-04-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190421_2121'),
        ('main', '0006_auto_20190421_2257'),
    ]

    operations = [
    ]
