# Generated by Django 2.2 on 2019-05-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190501_0302'),
        ('main', '0006_auto_20190501_0710'),
    ]

    operations = [
    ]
