# Generated by Django 2.2.4 on 2020-04-23 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20200423_0243"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="whitelistentry",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
