# Generated by Django 2.2 on 2019-05-02 23:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20190502_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityentry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='communityentry',
            name='race',
        ),
        migrations.RemoveField(
            model_name='communityentry',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='communityentry',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='communityentry',
            name='census_blocks_multipolygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
