# Generated by Django 2.2.4 on 2020-04-23 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_auto_20200423_1943"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization", name="email_whitelist",
        ),
        migrations.AddField(
            model_name="whitelistentry",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="whitelistentry",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Organization",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="WhiteListLink",),
    ]
