# Generated by Django 2.2.4 on 2020-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_auto_20200424_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(blank=True),
        ),
    ]
