# Generated by Django 2.2.4 on 2020-04-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_auto_20200424_1013"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Organization",
            ),
        ),
    ]
