# Generated by Django 2.2.4 on 2020-05-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_communityentry_organization"),
        ("main", "0004_remove_communityentry_my_community"),
    ]

    operations = []
