# Generated by Django 2.2.4 on 2020-05-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_auto_20200501_0001"),
        ("main", "0014_merge_20200501_1523"),
    ]

    operations = []
