# Generated by Django 2.2.10 on 2020-05-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_auto_20200519_1627"),
    ]

    operations = [
        migrations.RenameModel(old_name="Campaigns", new_name="Campaign",),
    ]
