# Generated by Django 2.2.6 on 2020-05-17 23:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_communityentry_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityentry",
            name="user_phone",
            field=phone_field.models.PhoneField(default="", max_length=31),
        ),
    ]
