# Generated by Django 2.2.10 on 2020-05-19 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_auto_20200519_1631"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.Campaign",
                    ),
                ),
            ],
        ),
    ]
