# Generated by Django 2.2.6 on 2020-05-17 23:09

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_communityentry_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='user_phone',
            field=phone_field.models.PhoneField(default='', max_length=31),
        ),
    ]
