# Generated by Django 2.2.10 on 2020-05-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_campaigntoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityentry",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Campaign",
            ),
        ),
    ]
