# Generated by Django 2.2.6 on 2020-05-20 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ("entry_ID",)},
        ),
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.AddField(
            model_name="address",
            name="entry_ID",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.CommunityEntry",
            ),
        ),
    ]
