# Generated by Django 2.2.6 on 2020-05-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_communityentry_campaign"),
        ("main", "0023_auto_20200520_1755"),
    ]

    operations = []
