# Generated by Django 2.2.6 on 2020-05-23 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200523_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
