# Generated by Django 2.2.10 on 2020-05-26 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_communityentry_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="description",
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
