# Generated by Django 3.0.7 on 2020-06-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_remove_communityentry_user_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="communityentry", name="tags",),
        migrations.DeleteModel(name="Tag",),
    ]
