# Generated by Django 2.2.13 on 2020-06-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_auto_20200611_2139"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WhiteListEntry",
            new_name="AllowList",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="is_whitelisted",
            new_name="is_allowlisted",
        ),
    ]
