# Generated by Django 2.2.13 on 2020-06-24 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_auto_20200611_2139"),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                (
                    "abbr",
                    models.CharField(default="", max_length=2, unique=True),
                ),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
