# Generated by Django 2.2.13 on 2020-06-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_state"),
    ]

    operations = [
        migrations.AlterModelTable(name="state", table="states",),
    ]
