# Generated by Django 2.2.13 on 2020-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_auto_20200624_1549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="content",
            field=models.CharField(default="", max_length=500),
        ),
    ]
