# Generated by Django 2.2.13 on 2020-06-24 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_auto_20200624_1941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="content1",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
