# Generated by Django 2.2.13 on 2020-06-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_auto_20200624_1947"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state", old_name="content1", new_name="content",
        ),
        migrations.RemoveField(model_name="state", name="content2",),
    ]
