# Generated by Django 2.2.13 on 2020-06-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0038_auto_20200624_1948"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="state",
            table="state",
        ),
    ]
