# Generated by Django 2.2.13 on 2020-06-26 20:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0039_auto_20200624_2247"),
    ]

    operations = [
        migrations.RenameField(
            model_name="state",
            old_name="content",
            new_name="content1",
        ),
        migrations.AddField(
            model_name="state",
            name="content2",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="state",
            name="content3",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="state",
            name="content4",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
