# Generated by Django 2.2.13 on 2020-06-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_auto_20200626_1624"),
        ("main", "0040_auto_20200626_2045"),
    ]

    operations = []
