# Generated by Django 2.2.13 on 2020-07-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_auto_20200629_1138"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Campaign",
            new_name="Drive",
        ),
        migrations.RenameModel(
            old_name="CampaignToken",
            new_name="DriveToken",
        ),
    ]
