# Generated by Django 2.2.13 on 2020-07-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_auto_20200704_0622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.Organization",
            ),
        ),
    ]
