# Generated by Django 2.2.13 on 2020-07-21 05:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0045_auto_20200704_0622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="user_polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
