# Generated by Django 2.2.13 on 2020-07-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_auto_20200727_2002"),
        ("main", "0046_auto_20200727_0712"),
    ]

    operations = []
