# Generated by Django 2.2.13 on 2020-07-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_report"),
        ("main", "0047_merge_20200728_0101"),
    ]

    operations = []
