# Generated by Django 2.2.13 on 2020-07-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0047_merge_20200728_0101"),
        ("main", "0047_auto_20200721_0731"),
    ]

    operations = []
