# Generated by Django 2.2.13 on 2020-08-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_auto_20200731_2122"),
        ("main", "0048_merge_20200729_1341"),
    ]

    operations = []
