# Generated by Django 2.2.13 on 2020-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0049_auto_20200731_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="drive",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
