# Generated by Django 2.2.13 on 2020-08-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_drive_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowlist",
            name="drive",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.Drive",
            ),
        ),
    ]
