# Generated by Django 2.2.13 on 2020-08-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_allowlist_drive"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityentry",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
