# Generated by Django 2.2.13 on 2020-08-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_merge_20200803_1853"),
        ("main", "0052_communityentry_private"),
    ]

    operations = []
