# Generated by Django 2.2.13 on 2020-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_merge_20200811_0708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="private",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
