# Generated by Django 2.2.13 on 2020-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0053_auto_20200811_1829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="block_groups",
            field=models.ManyToManyField(blank=True, to="main.BlockGroup"),
        ),
    ]
