# Generated by Django 2.2.13 on 2020-10-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0056_auto_20200908_1604"),
        ("main", "0054_auto_20200811_1957"),
    ]

    operations = []
