# Generated by Django 2.2.13 on 2020-10-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0056_auto_20200908_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="drive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="main.Drive",
            ),
        ),
    ]
