# Generated by Django 2.2.13 on 2020-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_auto_20201022_1603"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drive",
            old_name="is_address_required",
            new_name="require_user_addresses",
        ),
    ]
