# Generated by Django 2.2.13 on 2020-12-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_auto_20201120_0559"),
        ("main", "0058_auto_20201026_1544"),
        ("main", "0058_auto_20201023_0855"),
    ]

    operations = []
