# Generated by Django 2.2.13 on 2020-12-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20201023_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='state',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
