# Generated by Django 2.2.13 on 2020-12-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_merge_20201201_0250'),
        ('main', '0060_merge_20201201_1009'),
    ]

    operations = [
    ]
