# Generated by Django 2.2.13 on 2020-12-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0061_merge_20201201_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="drive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.Drive",
            ),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.Organization",
            ),
        ),
    ]
