# Generated by Django 2.2.13 on 2020-12-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0062_auto_20201201_1733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="drive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="main.Drive",
            ),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="main.Organization",
            ),
        ),
    ]
