# Generated by Django 2.2.13 on 2020-12-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0063_auto_20201201_1739"),
        ("main", "0059_merge_20201201_0226"),
    ]

    operations = []
