# Generated by Django 2.2.13 on 2020-12-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0057_merge_20201020_2006"),
        ("main", "0065_auto_20201202_0159"),
    ]

    operations = []
