# Generated by Django 2.2.13 on 2020-12-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0065_auto_20201202_0159"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityentry",
            name="population",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
