# Generated by Django 2.2.13 on 2020-12-29 22:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_frequentlyaskedquestion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
