# Generated by Django 2.2.13 on 2020-12-31 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20201229_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='state_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='main.State'),
        ),
    ]
