# Generated by Django 2.2.13 on 2020-12-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_communityentry_population'),
        ('main', '0070_communityentry_state_obj'),
    ]

    operations = [
    ]
