# Generated by Django 2.2.13 on 2021-01-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0072_signature"),
        ("main", "0066_merge_20201229_2049"),
    ]

    operations = []
