# Generated by Django 2.2.13 on 2021-03-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_organization_verified'),
        ('main', '0074_auto_20210301_1943'),
    ]

    operations = [
    ]
