# Generated by Django 2.2.13 on 2021-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_merge_20210319_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
