# Generated by Django 2.2.13 on 2021-05-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20210422_1442'),
        ('main', '0074_censusblock'),
    ]

    operations = [
    ]
