# Generated by Django 2.2.13 on 2021-05-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_merge_20210503_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='census_blocks',
            field=models.ManyToManyField(blank=True, to='main.CensusBlock'),
        ),
    ]
