# Generated by Django 2.2.13 on 2021-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_merge_20210503_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='custom_response',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='drive',
            name='custom_question',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
