# Generated by Django 2.2.13 on 2021-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_communityentry_census_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockgroup',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
