# Generated by Django 2.2.13 on 2021-05-14 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_drive_custom_question_example'),
        ('main', '0080_auto_20210505_1516'),
    ]

    operations = [
    ]
