# Generated by Django 2.2.20 on 2021-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0081_merge_20210514_0335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityentry",
            name="comm_activities",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="cultural_interests",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="custom_response",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="economic_interests",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AlterField(
            model_name="communityentry",
            name="other_considerations",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
    ]
