# Generated by Django 2.2.20 on 2021-06-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_merge_20210514_0226'),
        ('main', '0081_merge_20210514_0335'),
    ]

    operations = [
    ]
