# Generated by Django 2.2.20 on 2021-06-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0082_merge_20210604_0716"),
        ("main", "0082_auto_20210602_1439"),
    ]

    operations = []
