# Generated by Django 2.2.18 on 2021-06-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_merge_20210608_1746'),
        ('main', '0083_merge_20210609_0044'),
    ]

    operations = [
    ]
