# Generated by Django 2.2.18 on 2021-06-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20210611_1406'),
        ('main', '0084_auto_20210608_1629'),
    ]

    operations = [
    ]
