# Generated by Django 2.2.18 on 2021-06-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0086_merge_20210617_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="drive",
            name="coi_def_info",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AddField(
            model_name="drive",
            name="coi_def_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="drive",
            name="criteria_info",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AddField(
            model_name="drive",
            name="criteria_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="drive",
            name="redist_info",
            field=models.TextField(blank=True, default="", max_length=700),
        ),
        migrations.AddField(
            model_name="drive",
            name="redist_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="drive",
            name="units",
            field=models.CharField(
                choices=[
                    ("B", "Census Blocks"),
                    ("BG", "Census Block Groups"),
                ],
                default="block_groups",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="government",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="drive",
            name="description",
            field=models.CharField(
                default="A mapping drive for communities of interest",
                max_length=700,
            ),
        ),
    ]
