# Generated by Django 2.2.20 on 2021-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_merge_20210617_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='edit_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
