# Generated by Django 2.2.20 on 2021-07-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0087_signature_edit_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signature",
            old_name="edit_hash",
            new_name="edit_Hash",
        ),
    ]
