# Generated by Django 2.2.18 on 2021-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20210622_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='government',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
