# Generated by Django 2.2.18 on 2021-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20210630_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
