# Generated by Django 2.2.20 on 2021-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0088_auto_20210713_1540"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signature",
            old_name="edit_Hash",
            new_name="edit_hash",
        ),
    ]
