# Generated by Django 2.2.24 on 2021-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20210713_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
