# Generated by Django 2.2.24 on 2021-07-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_auto_20210701_1746'),
        ('main', '0088_image'),
    ]

    operations = [
    ]
