# Generated by Django 2.2.24 on 2021-07-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_communityentry_is_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityentry',
            name='is_final',
        ),
    ]
