# Generated by Django 2.2.24 on 2021-07-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_merge_20210713_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='coi_def_info',
            new_name='opt_coi_def_info',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='coi_def_title',
            new_name='opt_coi_def_title',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='criteria_info',
            new_name='opt_criteria_info',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='criteria_title',
            new_name='opt_criteria_title',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='redist_info',
            new_name='opt_redist_info',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='redist_title',
            new_name='opt_redist_title',
        ),
    ]
