# Generated by Django 2.2.24 on 2021-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_remove_communityentry_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityentry',
            name='is_final',
            field=models.BooleanField(default=True),
        ),
    ]
