# Generated by Django 2.2.24 on 2021-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_communityentry_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
