# Generated by Django 2.2.24 on 2021-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20210714_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='description',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='drive',
            name='units',
            field=models.CharField(choices=[('BG', 'Census Block Groups'), ('B', 'Census Blocks')], default='Census Block Groups', max_length=50),
        ),
    ]
