# Generated by Django 2.2.24 on 2021-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20210727_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityentry',
            name='is_final',
            field=models.BooleanField(default=True),
        ),
    ]
