# Generated by Django 2.2.24 on 2021-07-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20210719_1642'),
        ('main', '0087_auto_20210629_1823'),
        ('main', '0090_remove_communityentry_community_hash'),
    ]

    operations = [
    ]
