# Generated by Django 2.2.24 on 2021-07-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20210720_1637'),
        ('main', '0095_auto_20210723_1545'),
        ('main', '0095_auto_20210720_2234'),
    ]

    operations = [
    ]
