# Generated by Django 2.2.24 on 2021-07-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_merge_20210727_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
