# Generated by Django 2.2.24 on 2021-10-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20210727_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='draw_layer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
