# Generated by Django 2.2.24 on 2021-07-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20210720_1652'),
        ('main', '0097_auto_20210727_2309'),
    ]

    operations = [
    ]
