# Generated by Django 2.2.24 on 2021-12-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_drive_draw_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='flytox',
            field=models.FloatField(blank=True, default='0.0'),
        ),
        migrations.AddField(
            model_name='drive',
            name='flytoy',
            field=models.FloatField(blank=True, default='0.0'),
        ),
    ]
