# Generated by Django 2.2.24 on 2021-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20211210_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='flytox',
            field=models.FloatField(blank=True, default='0.0', help_text='Longitude'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='flytoy',
            field=models.FloatField(blank=True, default='0.0', help_text='Latitude'),
        ),
    ]
