# Generated by Django 2.2 on 2019-04-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_districter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_polgyon',
            new_name='entry_polygon',
        ),
    ]
